### ISSUE TITLE
Inspiration: fuse-ext2

### ISSUE THREAD

**Issue by pwnall** [gerard/ext4fuse#14]
I couldn't get ext4fuse to work on my Leopard install, but fuse-ext2 worked without a hassle. I'm posting a link here for other people who want to get their files, and so gerard can maybe use the code there as an inspiration.

http://alperakcan.org/?open=projects&project=fuse-ext2

**Comment by SlySven** [comment]
That URL has been hijacked/orphaned and does NOT go to the resource expected :open_mouth: - the last good version seems to be available from the [Wayback Machine's capture on 2012/09/12](http://web.archive.org/web/20120919174251/http://alperakcan.org:80/?open=projects&project=fuse-ext2)...! :sunglasses:
