### ISSUE TITLE
Mounting an ext4 partition shows no errors, but mount point "disappears"...

### ISSUE THREAD

**Issue by InfernoZeus** [gerard/ext4fuse#26]
I've installed osxfuse 2.6.2 and ext4fuse 0.1.3 using Homebrew. I mount an ext4 partition:

```
sudo ext4fuse /dev/disk1s2 /Users/Ben/extDrive/
```

which works without an error messages, but when I try to view the files, I get the following error message: 

```
$ ls -l /Users/Ben/extDrive 
ls: /Users/Ben/extDrive: No such file or directory
```

and the folder also doesn't show up if I list everything in `/Users/Ben`.

It's definitely mounted though, as `umount` autosuggests the path, and successfully unmounts the drive without errors. (Running it again gives an error message about the path not being currently mounted.)

Any idea what's causing this issue?

**Comment by olsonpm** [comment]
Works if I forego 'sudo' e.g. `ext4fuse /dev/disk1s2 ./extDrive`
